### ISSUE TITLE
Aggregate.cats payloadSize is wrong

### ISSUE THREAD

**Issue by Alexhuszagh** [nemtech/catbuffer#11]
The aggregate.cats schema [defines](https://github.com/nemtech/catbuffer/blob/master/schemas/aggregate/aggregate.cats#L7) payload size an 8-bit integer:

```cats
# binary layout for an aggregate transaction header
struct AggregateTransactionHeader
	# transaction payload size in bytes
	# \note this is the total number of bytes occupied by all sub-transactions
        payloadSize = uint8
```

However, the NEM2 library defines it [differently](https://github.com/nemtech/nem2-library-js/blob/master/src/buffers/AggregateTransactionBuffer.js#L375) as a 32-bit integer:

```js
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} transactionsSize
 */
Catapult.Buffers.AggregateTransactionBuffer.addTransactionsSize = function (builder, transactionsSize) {
	builder.addFieldInt32(7, transactionsSize, 0);
};
```

I believe the latter is correct, since only allowing 255 bytes for a payload size seems... off.

**Comment by rg911** [comment]
You are right, this is confirm already. We had a chat on Mattermost with core devs, Uint32 should be correct 👍

**Comment by Alexhuszagh** [comment]
@rg911 Should I submit a PR then?
