### ISSUE TITLE
[f2] namespace_registration.cats new registrationType order is not deserialization friendly.

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catbuffer#13]
Hi Team,

I'm applying the java catbuffer generator to the new f2 schemas. I've found that the new order in the namespace registration transaction generates a broken code. 

https://github.com/nemtech/catbuffer/blob/fushicho2/schemas/namespace/namespace_registration.cats

The problem is that you need to know the registration type in order to know if the binary includes a `duration` or a `parentId`. In the new order, the registration type comes after those values. 

It's probably easier to get the problem in code, this is the java constructor. We may have a similar problem in TS.

![image](https://user-images.githubusercontent.com/5390558/68230999-7d439a00-fffa-11e9-94a0-e0da0a22d562.png)

I could spend some time changing the generator or patching the generated code but I'm wondering if there is any technical reason to change the field order in the namespace registration transaction. Another problem is that if the duration and the parent id have different sizes, it would be harder to deserialize the transaction correctly as the `registrationType` could be serialized in a different position in the byte array.

Is it possible to rollback that field order change?

**Comment by Jaguar0625** [comment]
This is by design. @Wayonb already updated the java generator to account for this.
