### ISSUE TITLE
path incorrect for ../HEADER.inc file

### ISSUE THREAD

**Issue by sleepyOwl14** [nemtech/catbuffer#16]
relative path is incorrect for `../HEADER.inc`, in `main.py`, `scripts/generate_all.sh` and `Readme.md`

**Comment by Vektrat** [comment]
i believe it is intended to have user-provided files outside the project bounds, unsure if in this case it'd make more sense to have the HEADER.inc file within the project though, this is up to the core team

**Comment by Jaguar0625** [comment]
Fixed in 4ae4412.
