### ISSUE TITLE
Add resolution statement and state schema to all.cat

### ISSUE THREAD

**Issue by rg911** [nemtech/catbuffer#21]
The new `resolution_statement` and set of `state` schema is missing from the `all.cat` class.

**Comment by gimer** [comment]
imo state should probably not be in all.cat (it should only have model related things - so resolution_statement is probably ok)

@Jaguar0625 what's your take?

**Comment by Jaguar0625** [comment]
i'm unsure if we want all.cat vs transactions.cat, receipts.cat, etc

**Comment by fboucquez** [comment]
The all.cats is for the generators, to simply how the artifacts (npm, maven) are generated, built and published. If we split, we need to call the main.py multiple times, regenerating files and we may have problems if not all the models are in memory when generating from one input.
