### ISSUE TITLE
'no definition for referenced property "payloadSize"'

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catbuffer#22]
When trying to generate an Aggregate transaction builder CatsParse failed with the exception below.  The problem is due to payloadSize getting defined in a different struct than where its used.

 python3 main.py --schema schemas/aggregate/aggregate.cats --generator cpp_builder
Traceback (most recent call last):
  File "/Users/tbdev/code/catbuffer/catparser/CatsParser.py", line 31, in process_line
    self._process_line(line)
  File "/Users/tbdev/code/catbuffer/catparser/CatsParser.py", line 88, in _process_line
    self.active_parser.append({**parse_result, **partial_descriptor})
  File "/Users/tbdev/code/catbuffer/catparser/StructParser.py", line 29, in append
    self._require_known_property(property_type_descriptor['size'])
  File "/Users/tbdev/code/catbuffer/catparser/StructParser.py", line 47, in _require_known_property
    raise CatsParseException('no definition for referenced property "{0}"'.format(property_name))
catparser.CatsParseException.CatsParseException: no definition for referenced property "payloadSize"

# binary layout for an aggregate transaction header
struct AggregateTransactionHeader
        # transaction payload size in bytes
        # \note this is the total number of bytes occupied by all sub-transactions
        payloadSize = uint32

# binary layout for an aggregate transaction
struct AggregateTransaction
        const uint8 version = 2
        # aggregate complete
        const EntityType entityType = 0x4141

        inline Transaction
#       inline AggregateTransactionHeader
        payloadSize = uint32
        size = uint32
        transactions = array(byte, payloadSize)
        cosignatures = array(byte, size - payloadSize)

**Comment by Jaguar0625** [comment]
Fixed in 199c607.
