### ISSUE TITLE
The cosignatures' size in the aggregate.cats is incorrect.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catbuffer#23]
Current the size of cosignatures is set to size - payloadSize.
cosignatures = array(byte, size - payloadSize)

The above does not take into account the size of the main transaction object plus the size of payloadSize.  It should be 
cosignatures = array(byte, size - payloadSize - sizeof(Transaction) - sizeof(uint32) )

**Comment by Jaguar0625** [comment]
Fixed in 199c607.
