### ISSUE TITLE
Remove keccak_256

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catbuffer#30]
Reported in https://github.com/nemtech/symbol-sdk-java/issues/265#issuecomment-611456497

The LockSecretType `keccak_256` is not available in [catapult-server](https://github.com/nemtech/catapult-server/blob/ed000ac9b415639699cf2eb6021e31d0f306ebb2/plugins/txes/lock_secret/src/model/LockHashAlgorithm.h) anymore but the change has not been applied to the [schema](https://github.com/nemtech/catbuffer/blob/master/schemas/lock_secret/lock_secret_types.cats#L7).

**Comment by fboucquez** [comment]
I've tested the new hash algorithms, the indexes need to be changed too

https://github.com/nemtech/symbol-openapi/blob/master/spec/plugins/lock_secret/schemas/LockHashAlgorithmEnum.yml

New values are:

  * 0 (Op_Sha3_256) - Proof is hashed using SHA3-256.
  * 1 (Op_Hash_160) - Proof is hashed twice: first with SHA-256 and then with RIPEMD-160 (bitcoin's OP_HASH160).
  * 2 (Op_Hash_256) - Proof is hashed twice with SHA3-256 (bitcoin's OP_HASH256).
