### ISSUE TITLE
Duplicated AccountRestrictionFlags

### ISSUE THREAD

**Issue by rg911** [nemtech/catbuffer#36]
Since the last commit changed `ExtednedAccountRestrictionFlags` to `AccountRestrictionFlags` in `State`, it duplicates with the same class in `restriction_account (transaction)`

https://github.com/nemtech/catbuffer/commit/dc15fe0490a2a4f3c0811c00435e8f061a5093ca

**Comment by Jaguar0625** [comment]
fixed in 63782d6c70a6c607831e79b9f294965ec42310ac.
