### ISSUE TITLE
No way to assign more than one possible type 

### ISSUE THREAD

**Issue by CrackTheCode016** [nemtech/catbuffer#36]
While writing a schema for `RootNamespaceHistorySerializer`, I noticed that I could not assign the two possible types for a [namespace alias](https://github.com/nemtech/catapult-server/blob/95e0c6a1d700aedb9ca60faaf2b535f587012d7f/plugins/txes/namespace/src/state/RootNamespaceHistorySerializer.cpp#L41) in `cats`.  It could be beneficial to have something like this: 
```
enum AliasType : MosaicId | Address 
    ...

namespaceAlias = AliasType
```

Or something similar.   Thanks!

**Comment by gimer** [comment]
actually, there is already a way to do this using introduced conditionals...
```
aliasType = AliasType # enum
mosaicId = MosaicId if aliasType equals mosaic # this compares field aliasType against constant AliasType.Mosaic
address = Address if aliasType equals address # this compares field aliasType against constant AliasType.Address
```

(compare with RegisterNamespaceTransactionBody)

although writing generator that will **properly** handle this, might be tricky

**Comment by Jaguar0625** [comment]
we currently assume that all parts of union are same size, but this should work as long as generators are updated 

please coordinate with @Wayonb to update java generator

**Comment by Wayonb** [comment]
Try the code as @gimer suggested.  If it doesn't work with the Java generator then let me know.

**Comment by CrackTheCode016** [comment]
> Try the code as @gimer suggested. If it doesn't work with the Java generator then let me know.

Code by @gimer worked, and Java generator also worked just fine with it @Wayonb.  Thanks guys!

**Comment by Jaguar0625** [comment]
closing - resolved using `if` syntax.
