### ISSUE TITLE
AccountRestrictionType should be AccountRestrictionFlags

### ISSUE THREAD

**Issue by Wayonb** [nemtech/catbuffer#5]
AccountRestrictionType is a flag enum and should have been called AccountRestrictionFlags similar to the MosaicFlags.  The catbuffer generators doesn't have away to differentiate a flag enums from a regular enum except for this naming convention.  This is esp important to Java since there is no builtin flags enum type.

**Comment by fboucquez** [comment]
In the Java SDK I had to hack my way by adding all the possible enum
values. Those values are defined in the open api. Is this a bug in the
generator or in catbuffer?

**Comment by Jaguar0625** [comment]
Fixed in 37cfe21.
