### ISSUE TITLE
HeightActivityBuckets array size should be __FILL__ instead of static number

### ISSUE THREAD

**Issue by rg911** [nemtech/catbuffer#50]
https://github.com/nemtech/catbuffer/blob/cbc7743e9fb7539d82d007d985159586ba000f60/schemas/state/account_state.cats#L6

**Comment by gimer** [comment]
The 5 is expected to be there it is `Activity_Bucket_History_Size`
Please explain, this change does not look correct...

**Comment by rg911** [comment]
> The 5 is expected to be there, It is `Activity_Bucket_History_Size - Rollback_Buffer_Size`
> Please explain, this change does not look correct...

I see. so this is the max size for the activity buckets, and it can be less than 5 right?

**Comment by Jaguar0625** [comment]
the mongo mapper filters out [zero buckets](https://github.com/nemtech/catapult-server/blob/main/extensions/mongo/src/mappers/AccountStateMapper.cpp#L106) but they're always expected to be hashed and incorporated into the account state hash.
