### ISSUE TITLE
Is namespace_history_types.cats correct?

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catbuffer#62]
Is it possible that the following files are old?

https://github.com/nemtech/catbuffer/blob/main/schemas/state/namespace_history_types.cats
https://github.com/nemtech/catbuffer/blob/main/schemas/state/namespace_history.cats

Why the name history? Should it be entry?
Only root and not child state?
lifetime?  lifetimeStart? lifetimeEnd? Should it be startHeight and endHeight?

The schema looks different from the open API spec.
https://github.com/nemtech/symbol-openapi/blob/main/spec/plugins/namespace/schemas/NamespaceDTO.yml

**Comment by Jaguar0625** [comment]
It is supposed to map serialization in: https://github.com/nemtech/catapult-server/blob/main/plugins/txes/namespace/src/state/RootNamespaceHistorySerializer.cpp.

It is (intentionally) different than structure returned by mongo, which is more user friendly.

I reviewed it against the source, and it seems correct. If there is something specific that looks wrong, please provide more details.

**Comment by fboucquez** [comment]
Thank @Jaguar0625 , I'll have a closer look when trying to convert the user-friendly class type to the catbuffer builder. Is it possible to serialize the state of a child namespace?

**Comment by Jaguar0625** [comment]
> Is it possible to serialize the state of a child namespace?

Child namespaces are not serialized independently. They are serialized as part of owning root namespace.

**Comment by fboucquez** [comment]
Thanks @Jaguar0625 , got it. This one would be a bit more complicated because we only have information about the individual namespace. I would need to call rest multiple times to get the root and all the children.
